export const stationKey = 'PsjK9I6KvaofKMkDXzBX16E9SPRc2HvVCysFsW72';

export const cafeId = '3E2HW22GFIF5JPKWRKF1XBHOTP5JFPO0EOWBZWCEAQJQIEXC';

export const cafeSecret = 'WMGOCBDXCJVSFV0VG0NMQC5HNASM3AAVKKQ5VZEEC5HEOFQA';